---
title: "Cleaning pool `r params$pool` on `r Sys.Date()`"
params:
  pool: P096
  pool_vol: 1100
output:
  pdf_document: default
---

**Clean pooled ligations at a maximum volume of 360uL.**
```{r echo=FALSE, message=FALSE}
x <- ceiling(params$pool_vol/360)
first <- params$pool_vol/x
```
#First round

Separate the pool into `r x` vials of `r floor(first)` each.

Warm `r params$pool_vol*1.5`mL Ampure to room temperature.

Prep 70% ethanol fresh.

Add `r first*1.5`uL ampure to each vial and incubate at room temperature for 5 minutes.

Place on magnet for 2 minutes then remove supernatant.

Add 200uL 70% EtOH, incubate on magnet 30 seconds, remove supernatant.

Repeat: Add 200uL 70% EtOH, incubate on magnet 30 seconds, remove supernatant.

Place in evaporator for 5 minutes.

Double check that all EtOH is gone.

Add 40uL TE, pipet up and down to mix, incubate 5 minutes.

Place on magnet 2 minutes.

Add supernatants from all tubes in this pool to one new tube for a final volume of `r 40*x`

#Second round
Add `r 1.5 * 40*x` ampure to the final tube from the last round

Incubate 5 minutes

Place on magnet for 2 minutes, remove supernatant.

Add 200uL 70% EtOH, incubate on magnet 30 seconds, remove supernatant.

Repeat: Add 200uL 70% EtOH, incubate on magnet 30 seconds, remove supernatant.

Place in evaporator for 5 minutes.

Double check that all EtOH is gone.

Add 30uL TE, pipet up and down to mix, incubate 5 minutes.

Place on magnet 2 minutes.

Add supernatant to new tube labeled with pool name and date: `r params$pool`  `r Sys.Date()`
