---
title: "Clean 96 well plate of digests"
output:
  pdf_document: default
params:
  num_samples: 96
  vol_samples: 50
---

*This protocol assumes that you have read and understand the manufacturer’s instructions attached below.  Please read the full manufacturer’s instructions before using this abbreviated protocol.*

This protocol is to clean `r params$num_samples` `r params$vol_samples`uL samples of DNA.

1. Bring `r paste(params$vol_samples * params$num_samples * 1.5/1000, "mL", sep = " ")`  of AMPure to room temperature - takes about 5 minutes depending on temperature of lab.  

2. Make a 50mL falcon tube of 70% EtOH (important that this is made fresh daily) by filling the tube to 35mL 100% EtOH and filling to the 50mL mark with distilled water.  

3. Place ampure in a reagent resevoir.  

4. Add `r params$vol_sample * 1.5`uL of Ampure to each `r params$vol_sample`uL sample with a multichannel pipet, pipet up and down at least 3 times to mix.  

5. Incubate 5 min at room temperature.  

6. Place 4 yellow tip tray liners on the magnet so the pellet will form below the 40µL line.  

7. Put digest plate on magnet for 2 min.  

7. Discard supernatant once it is clear by pipeting ~150uL out of wells.  It is ok if you don't get all of the liquid but important not to disturb the pellet.  

7. Place the 50mL 70% EtOH in a new reagent reservoir.  

7. Add 200µL fresh 70% EtOH, incubate 30 sec, pipet ~250uL to remove EtOH from wells.  

8. Add 200µL fresh 70% EtOH, incubate 30 sec, pipet ~250uL to remove EtOH from wells.  

9. **New July 2018** Place the plate and magnet together in the Vacufuge plus, push the mode button until it says D-AL (dessicate alcohol) and set the timer for 5-7 minutes (at 8 minutes some of the pellets did not resuspend well).  

9. Check the wells for any remaining liquid.  If liquid remains, remove the magnet from the vacufuge, place an empty balance plate in the other side, and spin for 1 minute.  Then, pipet out the remaining fluid.

10. Add *45µL* 1x TE buffer to each well in order to keep the pellets moist, then go back and pipet up and down to mix.  

11. Incubate 5 min at room temperature on the benchtop (no magnet).  

11. Remove the yellow tray tip liners from the magnet and place the plate back on magnet for 1-2 minutes (until liquid appears clear).  

12. Pull 45µL of supernatant into a new labeled plate and seal with film (sometimes all 45uL does not come back, label as 40uL of sample regardless of how much fills pipet).  

13. Discard plate with pellets and move the 70% EtOH into the spraybottle for cleaning the benchtop.  

14. In the laboratory project in RStudio, open changedb.R and update the final_vol field for this digest plate to reflect the 40uL (or other volume if applicable) that was used to elute the DNA from the pellet.
