---
title: "add seqs to pcr pools"
output:
  pdf_document: default
params: 
  type: "anemones"
  id: "anem_table_id"
  db: "Leyte"
  first: NA
  last: NA

  
---

Access database.
```{r workspace, echo = F, message=FALSE}

source("../genomics/scripts/lab_helpers.R")
write <- write_db(params$db)
library(knitr)

# pull in entire db table
db <- read_db(params$db)
dat <- db %>% tbl(params$type) %>% collect()
```
Find the range of rows to be changed
# 3 rows have an old anem id but no anem_id, fixing in the database on 2018-10-15, MRS
```{r change}
dat <- db %>% 
  tbl(params$type) %>% 
  collect()

change <- dat %>% 
  filter(anem_id == 3122) %>% 
  mutate(correction = "Y", 
    corr_date = "2018-10-16", 
    corr_editor = "MRS", 
    corr_message = "Changed old_anem_id from 1250 to 1218 because 1250 was seen elsewhere during the same dive and 1218 is closer to where 3122 was mapped.", 
    old_anem_id = 1218)

dat <- change_rows(dat, change, params$id)

test <- dat %>% 
  filter(anem_id == 3122)
```


# Write to database
```{r write}
# backup 
backup <- leyte %>% 
  tbl(params$type) %>% 
  collect()

write_rds(backup, path = paste0("~/Documents/db_backups/", Sys.Date(), "_", params$type, ".Rdata"))

# dbWriteTable(write, params$type, dat, row.names = F, overwrite = T, append = F)
# dbDisconnect(write)
```

