---
title: "Digest in progress under construction"
output: html_notebook
---

*This protocol assumes that you have read and understand the manufacturer’s instructions attached below.  Please read the full manufacturer’s instructions before using this abbreviated protocol.*


Digest recipe 50µL rxn - use digest sheet in PCR worksheet, double check math:
(https://docs.google.com/spreadsheets/d/1LGt2WziwmGoJMluBcwmKfhZrGjZOlJLkVHf59-5cOV4/edit?usp=sharing) or the R code below

#####################################################################################

Copy the table into your lab notebook.

- Make the master mix recipe in 15mL falcon tube by following the amounts on the spreadsheet above
- split the master mix into 8 wells, use a multichannel pipet to pipet 20µL of master mix into each sample well.

- Do not add the master mix to all of the wells and then add the sample.  Because you are working with active enzymes, they should be the last things added to the master mix and the last step of plate preparation.
- Incubate PstI and MluCI at 37˚ for one hour - No benefit from incubating MluCI longer than one hour, PstI is active 2-4 hours, don’t need to heat kill digests

Clean the digests using 1.5x the volume of the digest (75µL) Ampure per sample. Put the plates on yellow lifts on the magnet so that the pellet is lower before you finish the alcohol steps.   Because these are in plates and it is difficult to get all of the elute out of the well, elute in 45µL of buffer and pull 40µL from the well to place in a new cleaned digest plate.  Record this volume of 40 on the Sample_Data spreadsheet, Digests Page in the buffer column - Ampure clean up protocol

Quantifiy - quant-it pico green - import the quantification results into the Sample_Data spreadsheet, Digests Page quant column.  For any sample with a negative quantification value, change the Ligated? column value to N/A (the rest should contain a formula that results in the value “FALSE”).  Also, add an _F to the extraction ID (not the digest ID) in the extraction ID column (example: PADE14_093E1516 becomes PADE14_093E1516_F).  This digest failed and so the sample should not reflect that a successful digest exits.
