---
title: "Samples that need sequencing as of `r Sys.Date()`"
output: html_notebook
---
```{r workspace echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
source("../genomics/scripts/gen_helpers.R")
source("../genomics/scripts/lab_helpers.R")
leyte <- read_db("Leyte")
lab <- read_db("Laboratory")
```

**Samples that have successfully completed sequencing**
These samples have passed Michelle's dDocent filters
```{r success}
# locate the genepop file and read as data frame
genfile <- "../genomics/data/seq17_03g95maf2q30dp15.gen"
genedf <- read_genepop(genfile)

# format the file-----------------------------

# remove columns of loci
genedf <- genedf %>% 
  select(names) %>% 
  rename(ligation_id=names)


# Just in case some of the samples are named with APCL before the ligation_id, create a search term to search for ligation ids within a name
ligid <- "(.+)(L\\d\\d\\d\\d)" 
# change all of the names to ligation id only
genedf$ligation_id <- genedf$ligation_id %>% str_replace(ligid,"\\2")

# get sample ids for these ligations ----------------------------
samples <- samp_from_lig(genedf)

if (nrow(samples) != nrow(genedf)){
  # are there duplicate ligation ids in genedf?
  no_dups <- distinct(genedf, ligation_id) 
    # that wasn't the issue, same number of rows in no_dups as in genedf

  # which ligation ids are in genedf that are not in samples?
  no_sample <- genedf %>% filter(!ligation_id %in% samples$ligation_id)
    # these 11 samples are problem samples that can't be matched to a sample
}else{
  print("All sequenced samples accounted for")
}

# write.csv(samples, file = paste("data/samples_successfully_seq_as_of_", Sys.Date(), ".csv", sep = "" ))

rm(no_dups, no_sample, genedf)

samples <- samples %>% 
  arrange(sample_id)

kable(samples, longtable=T) %>% 
  kable_styling(latex_options = "repeat_header") %>%
  add_header_above(c("Successfully sequenced" = 2))

```
