---
title: "Ordering lab supplies"
author: "Michelle Stuart"
date: "6/13/2018"
output:
  html_document: default
  pdf_document: default
---
```{r echo=FALSE, message=FALSE}
library(dplyr)
library(knitr)
```

I need to order lab supplies.

####Quantification of 7 digest plates

```{r, echo=FALSE, message=FALSE, warning=FALSE}
pico <- data.frame(NA)
pico <- pico %>% 
  mutate(
    num_samples = (96*7)+(8*7),
    final_vol_pico = 100*num_samples,
    vol_1x_TE = 0.995 * final_vol_pico,
    grenier_plate = ceiling(num_samples/96),
    pico = final_vol_pico - vol_1x_TE,
    tips_100 = 2*num_samples,
    tips_10 = num_samples,
    foil = grenier_plate, 
    seals = grenier_plate
  ) %>% 
  select(-NA., -final_vol_pico, -vol_1x_TE)
kable(pico)
```

####Extraction of 8 2018 APCL plates
```{r, echo=FALSE}
extr <- data.frame(NA)
extr <- extr %>% 
  mutate(num_samples = 736, 
    qiagen = ceiling(num_samples/96), 
    tips_300 = 7*qiagen, 
    plates = qiagen, 
    seals = qiagen) %>%
  select(-NA.)
```

####Quantify 8 plates of extracts
```{r, echo=FALSE}
pico2 <- data.frame(NA)
pico2 <- pico2 %>% 
  mutate(
    num_samples = 736,
    final_vol_pico = 100*num_samples,
    vol_1x_TE = 0.995 * final_vol_pico,
    grenier_plate = ceiling(num_samples/96),
    pico = final_vol_pico - vol_1x_TE,
    tips_100 = 2*num_samples,
    tips_10 = num_samples,
    foil = grenier_plate,
    seals = grenier_plate
  ) %>% 
  select(-NA., -final_vol_pico, -vol_1x_TE)
pico <- rbind(pico, pico2)
pico <- pico %>% 
  summarise(num_samples = sum(num_samples), 
    grenier_plate = sum(grenier_plate), 
    pico = sum(pico), 
    tips_100 = sum(tips_100), 
    tips_10 = sum(tips_10), 
    foil = sum(foil), 
    seals = sum(seals))
kable(pico)
rm(pico2)
```

####Digest 8 plates
```{r, echo=FALSE}
digest <- data.frame(NA)
digest <- digest %>% 
  mutate(
    num_samples = 736, 
    plates = ceiling(num_samples/96), 
    tips_100 = num_samples*2, 
    PstI = 0.2*(num_samples*1.1), 
    MluCI = 2*(num_samples*1.1),
    seals = 2*plates
    ) %>% 
  select(-NA.)
```

####Clean 8 plates
```{r, echo=FALSE}
clean <- data.frame(NA)
clean <- clean %>% 
  mutate(
    num_samples = 736, 
    vol_samples = 50,
    ampure = (num_samples*1.1)* 1.5 * vol_samples, 
    ethanol = 400 * (num_samples * 1.1), 
    tips_300 = num_samples * 4,
    tips_100 = num_samples * 3, 
    plates = ceiling(num_samples/96), 
    seals = plates) %>% 
  select(-NA.)
```

####Quantify 8 digest plates
```{r, echo=FALSE}
pico3 <- data.frame(NA)
pico3 <- pico3 %>% 
  mutate(
    num_samples = 736 * 1.1,
    final_vol_pico = 100*num_samples,
    vol_1x_TE = 0.995 * final_vol_pico,
    grenier_plate = ceiling(num_samples/96),
    pico = final_vol_pico - vol_1x_TE,
    tips_100 = 2*num_samples,
    tips_10 = num_samples,
    foil = grenier_plate, 
    seals = grenier_plate
  ) %>% 
  select(-NA., -final_vol_pico, -vol_1x_TE)
pico <- rbind(pico, pico3)
pico <- pico %>% 
  summarise(num_samples = sum(num_samples), 
    grenier_plate = sum(grenier_plate), 
    pico = sum(pico), 
    tips_100 = sum(tips_100), 
    tips_10 = sum(tips_10), 
    foil = sum(foil), 
    seals = sum(seals))
kable(pico)
rm(pico3)
```
####Merge these 4 tables into one grocery list
```{r, echo=FALSE}
# get rid of columns that aren't supplies
clean <- clean %>%
  select(-num_samples, -vol_samples) %>% 
  mutate(method = "clean")

digest <- digest %>% 
  select(-num_samples) %>% 
  mutate(method = "digest")

extr <- extr %>% 
  select(-num_samples) %>% 
  mutate(method = "extract")

pico <- pico %>% 
  select(-num_samples) %>% 
  mutate(method = "pico")

clean <- clean %>% 
  mutate(PstI = NA, 
    MluCI = NA, 
    qiagen = NA, 
    grenier_plate = NA, 
    pico = NA, 
    tips_10 = NA, 
    foil = NA)

digest <- digest %>% 
  mutate(ampure = NA, 
    ethanol = NA, 
    tips_300 = NA, 
    qiagen = NA, 
    grenier_plate = NA, 
    pico = NA, 
    tips_10 = NA, 
    foil = NA)

extr <- extr %>% 
   mutate(ampure = NA, 
    ethanol = NA, 
    grenier_plate = NA, 
    pico = NA, 
    tips_10 = NA, 
    foil = NA, 
     tips_100 = NA, 
     PstI = NA, 
    MluCI = NA)

pico <- pico %>% 
  mutate(ampure = NA, 
    ethanol = NA, 
     PstI = NA, 
    MluCI = NA,
    tips_300 = NA, 
    qiagen = NA, 
    plates = NA)

total <- rbind(clean, digest, extr, pico)

full <- total %>% 
  summarise(
    ampure = sum(ampure, na.rm = T) ,
      ethanol = sum(ethanol, na.rm = T) ,
      tips_300 = sum(tips_300, na.rm = T) ,
      tips_100 = sum(tips_100, na.rm = T) ,
      plates = sum(plates, na.rm = T) ,
      seals = sum(seals, na.rm = T) ,
      PstI = sum(PstI, na.rm = T) ,
      MluCI = sum(MluCI, na.rm = T) ,
      qiagen = sum(qiagen, na.rm = T) ,
      grenier = sum(grenier_plate, na.rm = T) ,
      pico = sum(pico, na.rm = T),
      tips_10 = sum(tips_10, na.rm = T) ,
      foil = sum(foil, na.rm = T)
    )
full <- tidyr::gather(full, key = "item", value = "qty")
kable(full)
```

