---
title: '`r paste("Pico Platereader Quantification for ", params$first, "-", params$last, sep = "")`'
params:
  file: ~/Downloads/2018-07-17-full.txt
  id: extraction_id
  first_sample: E4551
  last_sample: E5126
  type: extraction
output:
  pdf_document: default
---
```{r workspace, echo=FALSE, message=FALSE}
library(knitr)
library(stringr)
library(tidyverse)
library(kableExtra)
source("../genomics/scripts/lab_helpers.R")

# connect to database
lab <- write_db("Laboratory")
```

Once you have completed all of the steps in the quant_prep.pdf, it is time to import the data into the database and make a pdf note for your lab notebook

**Read in quantification results**  

1. Open the plate reader results file and pull in the data  

<!-- # tried to use readr here but it returns all NAs for the table -->
<!-- # dat1 <- read_table(file, skip = 6, n_max = 88, col_names = c("Sample", 	"Wells", 	"RFU_Values", 	"Concentration", 	"Mean_Conc", 	"SD", 	"CV", 	"Dilution", 	"AdjConc"	)) -->
```{r reader_results, echo=FALSE, message=FALSE}
# determine number of lines to skip before data begins
strs <- readLines(params$file, skipNul = T)
linestoskip <- which(strs == "Group: Unknowns") # the number of lines to skip
num_lines <- as.numeric(substr(params$last_sample, 2, 5)) - as.numeric(substr(params$first_sample, 2, 5)) + 1

# create a table that contains well locations and quantities
# nrows = 88 because that is a full plate
dat <- read.table(text=strs,  skip = linestoskip, sep = "\t", header = T, fill = T, stringsAsFactors = F, nrows = num_lines) %>% 
  rename(well = Wells) %>% 
  mutate(Sample = as.numeric(Sample)) %>% 
  arrange(Sample) %>% 
  select(Sample, well, AdjConc)
```
2. Connect names of samples from database
```{r sample_names, echo=FALSE}
# pull in the full database table
db_dat <- dbReadTable(lab, params$type)

# select your samples
if (params$type == "extraction"){
  samp <- db_dat %>%
    select(contains("id"), well, plate) %>% 
    # narrow down the results to just this batch
    filter(extraction_id >= params$first_sample, 
           extraction_id <= params$last_sample) %>% 
    # pull out col and row so that the samples can be sorted (not always in plates in id order)
    mutate(row = substr(well, 1, 1), 
           col = substr(well, 2, 3)) %>% 
    # sort by plate, then col, then row
    arrange(plate, col, row) 
}

 # define the plates that are present in this group
  plates <- samp %>% 
    select(plate) %>% 
    distinct() %>% 
    arrange(plate)
  
  # attach these plates to the quant data
  dat$plate <- NA
  for (i in 1:nrow(plates)){
    x = i*96
    y = x - 95
    dat <- dat %>% 
  mutate(plate = ifelse(Sample >= y & Sample <= x, plates$plate[i], plate))
  }

  
  samp <- samp %>% 
    # get rid of extra columns
    select(-row, -col)

# join the ids to the quantification data
quant1 <- left_join(samp, dat, by = c("plate", "well")) %>%
  select(contains("id"), AdjConc) %>%
  # rename the quant column so it can be joined to the db
  rename(quant = AdjConc) %>% 
  # remove any empty wells
  filter(!is.na(quant))
kable(quant1, longtable = T) %>% 
  kable_styling(latex_options = "repeat_header")


# the entire table was pulled in as dat above
if (params$id == "extraction_id"){
  change <- db_dat %>%
    filter(extraction_id %in% quant1$extraction_id)  %>%
    # don't bring in the quant column, will add that here
    select(-quant) 
}

# add in the new quants
ids <- change %>%
  select(contains("id"))
change <- left_join(change, quant1, by = c(names(ids)))

db_dat <- change_rows(db_dat, change, params$id)
```
#####Write these changes into the database
```{r echo=FALSE, message=FALSE}
# dbWriteTable(lab, params$type, db_dat, row.names = F, overwrite = T)
dbDisconnect(lab)
```
