---
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: sandstone
---

# Welcome to the Pinsky Lab!  

There are a few items to take care of now that you have joined the lab.  

## To Do List:
1. Join the [Pinsky Lab Google Group](https://groups.google.com/forum/#!forum/pinsky-lab) mailing list.
1. Connect to the [Pinsky Lab Google Drive](https://drive.google.com/drive/u/0/my-drive).   
    - Click the "Shared with Me" link on the left.
    - Right click on the Pinsky Lab folder and select Add to My Drive.  This will not affect the amount of storage available in your google drive.  
1. Read the [Lab Code of Conduct](https://github.com/pinskylab/policies/blob/master/code-of-conduct.md).  
1. Read the [Lab Data Management Policy](https://github.com/pinskylab/policies/blob/master/data-management.md).  
1. Write an [Independent Development Plan](https://myidp.sciencecareers.org).  

## Computing Resources
There are several computing resources available to serve your research computing needs.  
1. The lab server.  
1. The SEBS server "annotate".    
1. The Rutgers Advanced Research Computing cluster "amarel".    
1. The Rutgers Discovery Informatics cluster "caliburn".    
*Various lab members have differing levels of experience with each of these servers and can help you figure out what is best for your analysis.* 

## Guides and tutorials
1. [Pinsky Lab Cookbook]() is a resource of how to's put together by lab members to help you past the occasional obstacle that we all seem to run into.  
1. [Collaborative Writing Guide]()  
1. [Data Management Guide]()  
1. [Time Management Guide]()  
1. [Command line tutorial](https://www.udacity.com/wiki/ud775/command-line-instructions) and [more help with the command line](https://classroom.udacity.com/courses/ud595/lessons/4597278561/concepts/46968695970923)  
1. [Git and GitHub tutorial](https://classroom.udacity.com/courses/ud775)
1. [Happy Git with R tutorial](https://happygitwithr.com)
