---
title: "Assign barcodes"
output: html_notebook
---

This script assigns barcodes to ligations based on well location.

Import the most recent batch of ligations that need barcode assignment
```{r echo=FALSE, message=FALSE}
source("../genomics/scripts/lab_helpers.R")

lab <- write_db("Laboratory")

lig <- dbReadTable(lab, "ligation") %>% 
  filter(is.na(barcode_num)) %>% 
# make sure the number of obs looks correct
select(ligation_id, well, pool, barcode_num) %>% 
# split out the wells into rows and columns
  mutate(row = substr(well, 1, 1), 
    col = as.numeric(substr(well, 2, 3))) %>%
  arrange(pool, col, row)

lig <- lig %>% 
  mutate(barcode_num = rep(1:48, 48))
# the formula for this repeat is barcode numbers 1 - 48, repeated over 48 pools

# double check that all of the same wells got the same barcode number
check <- lig %>% 
  group_by(well, barcode_num) %>% 
  distinct() %>% 
  summarise(count = n())
```
Add this to the database
```{r echo=FALSE, message=FALSE}
change <- lig %>% 
  select(-row, -col, -well, -pool)

lig <- dbReadTable(lab, "ligation")
change2 <- lig %>% 
  filter(ligation_id %in% change$ligation_id) %>% 
  select(-barcode_num)
change <- left_join(change, change2)

lig <- change_rows(lig, change, "ligation_id")

# dbWriteTable(lab, "ligation", lig, row.names = F, overwrite = T)
# dbDisconnect(lab)
```

