---
title: "Pippin of pools on `r Sys.Date()`"
output: html_notebook
params:
  pools: P073, P074, P075, P076, P077, P078, P084
---

```{r}
x <- params$pools
cat(x)
```

*Follow the steps in the quick start guide next to the machine (first time use should use the spiral bound instructions, which are more detailed)*
1. Allow reagents to come to room temp for 1/2 hour.  

2. Add 10µL loading dye L to each sample (only 5 samples at a time).  

3. Load saved protocol for 375 tight on the computer.  

4. Calibrate machine.  

5. label each lane of cassette with Pool #.  

6. check buffer levels and gel in cassette (no breaks in gel).  

7. remove all buffer from elution wells with 100µL pipet.  

8. load 40µL buffer into each elution well.  

9. tape elution wells.  

10. make sure sample wells are completely full of buffer.  

11. remove 40µL buffer from each sample well and add 40µL sample.  

12. close lid and hit start - run should last ~1:15.  

After the run, take 40µL from the elution well and place it in a tube (o-ring if PCR is not immediate) labeled on top with the Pool # and on the side with
“Pippin’d - 375” - or whatever size range
Pool #
Date
